import type { CSSProperties } from "react";

/** Co-located styles for the project-context document picker. */
export const s = {
  header: { display: "flex", alignItems: "center", gap: 12, marginBottom: 6 } satisfies CSSProperties,
  title: { fontSize: 17, fontWeight: 700 } satisfies CSSProperties,
  subtitle: {
    fontSize: 13,
    color: "var(--text-muted)",
    margin: "10px 0 14px",
    lineHeight: 1.5,
  } satisfies CSSProperties,
  repoRow: { display: "flex", alignItems: "center", gap: 12, marginBottom: 12 } satisfies CSSProperties,
  repoLabel: { fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  repoSelect: { minWidth: 260 } satisfies CSSProperties,
  search: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "7px 11px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    width: 220,
    marginLeft: "auto",
  } satisfies CSSProperties,
  searchInput: {
    flex: 1,
    fontSize: 13,
    background: "transparent",
    border: "none",
    outline: "none",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  split: { display: "flex", gap: 16, alignItems: "flex-start" } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 8, flex: 1, minWidth: 0 } satisfies CSSProperties,
  row: (attached: boolean, selected: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 14px",
    borderRadius: 8,
    border: "1px solid " + (selected ? "var(--accent)" : "var(--border)"),
    background: attached ? "var(--bg-hover)" : "var(--bg-elevated)",
  }),
  pathButton: {
    flex: 1,
    minWidth: 0,
    textAlign: "left",
    background: "none",
    border: "none",
    padding: 0,
    fontSize: 13,
    color: "var(--text-primary)",
    cursor: "pointer",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  } satisfies CSSProperties,
  typeChip: {
    fontSize: 11,
    fontWeight: 600,
    color: "var(--accent)",
    background: "var(--accent)1a",
    padding: "2px 8px",
    borderRadius: 4,
    flexShrink: 0,
  } satisfies CSSProperties,
  size: { fontSize: 11, color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  preview: {
    flex: 1,
    minWidth: 0,
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: 14,
    maxHeight: 420,
    overflow: "auto",
  } satisfies CSSProperties,
  previewTitle: { fontSize: 13, fontWeight: 700, marginBottom: 4 } satisfies CSSProperties,
  previewHint: { fontSize: 11, color: "var(--text-muted)", marginBottom: 10 } satisfies CSSProperties,
  previewBody: {
    fontSize: 12,
    lineHeight: 1.6,
    whiteSpace: "pre-wrap",
    color: "var(--text-secondary)",
    margin: 0,
  } satisfies CSSProperties,
  trust: {
    fontSize: 12,
    color: "var(--text-muted)",
    marginTop: 16,
    lineHeight: 1.5,
  } satisfies CSSProperties,
  footer: { display: "flex", alignItems: "center", gap: 12, marginTop: 14 } satisfies CSSProperties,
  savedNote: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
} as const;
