/**
 * PrBriefCard — the four states (loading / error / empty / populated), the
 * negative criterion that nothing generates a brief on render, the
 * review-focus items as clickable controls, and the outdated / degraded /
 * pending edge states.
 */
import { describe, it, expect, afterEach, beforeEach, vi } from "vitest";
// `fireEvent`, not `@testing-library/user-event` — the latter is not a
// dependency of this package (see BlastCard.test.tsx / client INSIGHTS.md).
import { render, screen, cleanup, fireEvent } from "@testing-library/react";
import { NextIntlClientProvider } from "next-intl";
import type { PrBriefRecord } from "@devdigest/shared";
import briefMessages from "../../../../../../../../messages/en/brief.json";

let mockState: {
  data: PrBriefRecord | null | undefined;
  isLoading: boolean;
  isError: boolean;
};
let mutate: ReturnType<typeof vi.fn>;
let isPending: boolean;

vi.mock("@/lib/hooks/brief", () => ({
  usePrBrief: () => mockState,
  useGenerateBrief: () => ({ mutate, isPending }),
}));

import { PrBriefCard } from "./PrBriefCard";

beforeEach(() => {
  mockState = { data: undefined, isLoading: true, isError: false };
  mutate = vi.fn();
  isPending = false;
});
afterEach(cleanup);

function record(over: Partial<PrBriefRecord> = {}, brief: Partial<PrBriefRecord["brief"]> = {}): PrBriefRecord {
  return {
    pr_id: "pr1",
    head_sha: "abc123",
    pr_head_sha: "abc123",
    model: "gpt-4.1",
    generated_at: "2026-08-29T10:00:00.000Z",
    brief: {
      what: "Adds rate limiting to the review routes.",
      why: "Every review run is a paid model call.",
      risk_level: "high",
      risks: [
        {
          kind: "regression",
          title: "Shared limiter state",
          explanation: "The limiter is process-local, so a second instance doubles the budget.",
          severity: "high",
          file_refs: ["src/app.ts"],
        },
      ],
      review_focus: [
        { file: "src/a.ts", line: 12, reason: "The limiter is wired here." },
        { file: "src/b.ts", line: null, reason: "New config key." },
      ],
      degraded: false,
      missing_inputs: [],
      ...brief,
    },
    ...over,
  };
}

function renderCard(onFocusFile = vi.fn()) {
  render(
    <NextIntlClientProvider locale="en" messages={{ brief: briefMessages }}>
      <PrBriefCard prId="pr1" onFocusFile={onFocusFile} />
    </NextIntlClientProvider>
  );
  return onFocusFile;
}

describe("PrBriefCard — no brief yet", () => {
  it("renders the empty state with a generate action, and generates nothing on render", () => {
    mockState = { data: null, isLoading: false, isError: false };
    renderCard();

    expect(screen.getByText("Brief not available yet.")).toBeInTheDocument();
    // A 404 is an empty state, never an error (AC-39, AC-NF-09).
    expect(screen.queryByText("Could not load the PR brief.")).not.toBeInTheDocument();
    // Nothing fires on mount — the CTA is the only call site (AC-16, AC-38).
    expect(mutate).not.toHaveBeenCalled();

    fireEvent.click(screen.getByRole("button", { name: "Generate brief" }));
    expect(mutate).toHaveBeenCalledTimes(1);
    expect(mutate).toHaveBeenCalledWith(undefined);
  });
});

describe("PrBriefCard — populated", () => {
  it("shows the risk level, what/why, the risks and the provenance line", () => {
    mockState = { data: record(), isLoading: false, isError: false };
    renderCard();

    expect(screen.getByText("Risk level: High")).toBeInTheDocument();
    expect(screen.getByText("Adds rate limiting to the review routes.")).toBeInTheDocument();
    expect(screen.getByText("Every review run is a paid model call.")).toBeInTheDocument();
    expect(screen.getByText("Shared limiter state")).toBeInTheDocument();
    expect(screen.getByText(/Generated by gpt-4\.1/)).toBeInTheDocument();
  });

  it("renders review-focus items as controls showing their reason, and reports the activated file and line", () => {
    mockState = { data: record(), isLoading: false, isError: false };
    const onFocusFile = renderCard();

    expect(screen.getByText("The limiter is wired here.")).toBeInTheDocument();
    expect(screen.getByText("New config key.")).toBeInTheDocument();

    fireEvent.click(screen.getByRole("button", { name: "Open src/a.ts in Files changed" }));
    expect(onFocusFile).toHaveBeenCalledWith("src/a.ts", 12);

    fireEvent.click(screen.getByRole("button", { name: "Open src/b.ts in Files changed" }));
    expect(onFocusFile).toHaveBeenLastCalledWith("src/b.ts", null);
  });

  it("offers a regeneration control distinct from the first-generation CTA", () => {
    mockState = { data: record(), isLoading: false, isError: false };
    renderCard();

    expect(screen.queryByRole("button", { name: "Generate brief" })).not.toBeInTheDocument();
    fireEvent.click(screen.getByRole("button", { name: "Regenerate brief" }));
    expect(mutate).toHaveBeenCalledWith({ force: true });
  });
});

describe("PrBriefCard — edge states", () => {
  it("says so explicitly rather than rendering an empty list when there are no risks", () => {
    mockState = {
      data: record({}, { risks: [], risk_level: "none" }),
      isLoading: false,
      isError: false,
    };
    renderCard();

    expect(screen.getByText("No notable risks flagged.")).toBeInTheDocument();
    expect(screen.queryByRole("list")).not.toBeInTheDocument();
    expect(screen.getByText("Risk level: None")).toBeInTheDocument();
  });

  it("warns that the brief is outdated when the head SHAs differ, and still offers regeneration", () => {
    mockState = {
      data: record({ head_sha: "old111", pr_head_sha: "new222" }),
      isLoading: false,
      isError: false,
    };
    renderCard();

    expect(
      screen.getByText("Generated against an older commit — regenerate it to match the current head.")
    ).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Regenerate brief" })).toBeInTheDocument();
  });

  it("names the unavailable inputs while degraded", () => {
    mockState = {
      data: record(
        {},
        {
          degraded: true,
          missing_inputs: [
            { kind: "intent", status: "absent" },
            { kind: "project_context", status: "unreachable" },
          ],
        }
      ),
      isLoading: false,
      isError: false,
    };
    renderCard();

    expect(
      screen.getByText(
        "Partial brief — these inputs were unavailable: PR intent (not recorded), project context (unreachable)."
      )
    ).toBeInTheDocument();
  });

  it("shows the pending state and disables the control while generating", () => {
    isPending = true;
    mockState = { data: record(), isLoading: false, isError: false };
    renderCard();

    expect(screen.getByText("Generating the brief…")).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Regenerate brief" })).toBeDisabled();
  });

  it("disables the generate CTA while a first generation is in flight", () => {
    isPending = true;
    mockState = { data: null, isLoading: false, isError: false };
    renderCard();

    expect(screen.getByRole("button", { name: "Generate brief" })).toBeDisabled();
  });
});
